#+OPTIONS: toc:nil num:nil tags:nil
#+OPTIONS: H:4
# \bibliography{notes}
#+BEGIN_HTML
---
layout: post
title: Research notes
description: Notes and readings
tags: graphics visualisation
categories: generic
comments: true
---
#+END_HTML

** Readings
*** Statistician Heal Thyself: Have We Lost the Plot? :graphics:visualisation:
  <2016-06-28 Tue 11:35>

Gordon, I., & Finch, S. (2015). [[http://www.tandfonline.com/doi/full/10.1080/10618600.2014.989324][Statistician Heal Thyself: Have We Lost the Plot?]] Journal of Computational and Graphical Statistics: A Joint Publication of American Statistical Association, Institute of Mathematical Statistics, Interface Foundation of North America, 24(4), 1210–1229.

- this is an article about graphics in science and statistics journals
- I think graphical display of data is much easier to parse than tabled data
  - but many (applied) journals specify a maximum of figures per article!
  #+BEGIN_QUOTE
  a high quality graph should be able to be interpreted without elaboration
  #+END_QUOTE
- Figure 1 shows a cluttered display
  - I think there's a ggplot2 function to push labels apart
  - yes, here it is: [[https://github.com/slowkow/ggrepel][ggrepel]]
- Figure 2 provides a redesign
  - basically a small multiples plot
  - this is an improvement, but if the relationship is not monotone, then this figure would look a bit messy
- Figure 3 provides a scatterplot alternative
  - the authors suggest that it is easy to see that average lifespan increases with education, but I find this difficult
  - I can more easily see the decrease in lifespan variation with increasing education though
- Principle 3:
  #+BEGIN_QUOTE
  Use good alignment on a common scale for quantities to be compared.
  #+END_QUOTE
  - pie charts and stacked bar charts fail this principle
    - stacked bar charts because only one category (the bottom one) is aligned against the common axis
  - panel plots also fail this?
- The figures in the article themselves are fuzzy
  - perhaps the authors could have taken their own advice?!
- Detection was found to be the main issue
  - This refers to how we find out about features of the graph
- They provide a checklist at the end of the article for those producing graphics
