#+OPTIONS: toc:nil num:nil tags:nil
#+OPTIONS: H:4
#+BEGIN_HTML
---
layout: post
title: Macro's for org-mode images
description: Daily notes
tags: emacs org-mode
categories:
comments: true
---
#+END_HTML

** Notes
*** Export dependent image extensions			      :emacs:orgmode:
  <2016-07-06 Wed 12:52>

I use emacs [[http://orgmode.org/][org-mode]] to prepare documents, presentations etc. Orgmode+babel allows for literate programming, e.g. by including R script within the document itself. Other examples of such documents are .Rnw documents that combine latex and R (via knitr) or .Rmd documents that combine markdown and R (again via knitr)[fn:1].

Sometimes, I'll write an ~org~ document that I want to convert into both html and pdf formats. This is fine, until it comes to images. I prefer svg images for including into html, and of course $\LaTeX$ requires (prefers) pdf images for inclusion. Creating the two formats is easy; making extension choice depending on output format was a little more tricky.

Enter macros.

Macros are simply text snippets that contain arguments. When referenced, macros are expanded with their arguments in place. Further, macros can contain ~lisp~, so that you can do all sorts of cool trickery.

Now, to my example, for easy image insertion, dependent on output format. It's simply a matter of defining an appropriate macro, that when referenced will expand itself appropriately. You can see the code and usage in the gist below. If exporting to html, the macro will expand to ~fig-name.svg~, if pdf, it will expand to ~fig-name.pdf~.

#+BEGIN_HTML
<script src="https://gist.github.com/SteveLane/2149da48838e14db4a6871254f1c8c78.js"></script>
#+END_HTML

See the [[http://orgmode.org/manual/Macro-replacement.html][org-mode manual]] for more details on macros, as well as some pre-defined macros, e.g. for inserting the author and date.

*** Footnotes

[fn:1] I used markdown (and Rmarkdown) for a little while, however I still don't think they're flexible enough for cross-referencing figures etc. Plus, org-mode has some extra goodies for note-taking, tagging and scheduling that I like.
