#+OPTIONS: toc:nil num:nil tags:nil
#+OPTIONS: H:4
#+BEGIN_HTML
---
layout: post
title: Research notes
description: I just read this article and really enjoyed it
tags: biosecurity invasives MCMC
categories: biosecurity
comments: true
---
#+END_HTML

** Readings
*** Pathway-level biosecurity			 :biosecurity:invasives:MCMC:
<2016-08-25 Thu 09:19>

García-Díaz, P., Ross, J. V., Woolnough, A. P., & Cassey, P. (2016). /Managing the risk of wildlife disease introduction: pathway-level biosecurity for preventing the introduction of alien ranaviruses/. The Journal of Applied Ecology. http://doi.org/10.1111/1365-2664.12749

This paper provides a really interesting way of modelling the effect of various biosecurity activities on the introduction of ranaviruses, particularly into Australia. Figure 1 describes their whole modelling approach really nicely; rather than a flowchart, the authors present a sequence of nested circles, each representing various stages where biosecurity activities are in place. The outer ring denotes the whole pool of vectors (amphibians) for the virus, which breaks the inner rings when the sneaky buggers get through. It is very clear.

The model the authors use provides a nice description of this process; it's essentially a chain of arrivals. They have a negative binomial model for the number of amphibians arriving in a state at time t, which depends on human traffic arriving at that state. The rest of the models specify the number of detections: at the border, and post-border detcetions. Finally, they model the number of amphibians that are not detected by either border or post-border biosecurity activities. These are the blighters that may carry disease into established/native populations.

** Notes
*** state-space models				    :biosecurity:state:space:
 <2016-08-25 Thu 16:21>

 - I've spent some time stuffing around trying to shoehorn some state-space models into [[http://mc-stan.org/interfaces/rstan][Rstan]] for sampling, but stan doesn't sample discrete parameters
 - Looks like the best way is to move to jags
   - I think I'll look at [[http://mcmc-jags.sourceforge.net/][rjags]] (naturally)
